# Event source configuration for northwoods-events-v2
# Keep these IDs stable—they're used for filenames and UI filters.
# Window is controlled by main.py (defaults to today .. +120d).

- id: boulder-junction-tec
  name: "Boulder Junction (TEC)"
  type: tec_rest
  url: "https://boulderjct.org/"

- id: eagle-river-chamber-tec
  name: "Eagle River Chamber (TEC)"
  type: tec_rest
  url: "https://eagleriver.org/"

- id: st-germain-chamber-tec
  name: "St. Germain Chamber (TEC)"
  type: tec_rest
  url: "https://st-germain.com/"

- id: rhinelander-chamber-growthzone
  name: "Rhinelander Chamber (GrowthZone)"
  type: growthzone_html
  url: "https://business.rhinelanderchamber.com/events/calendar"

- id: lets-minocqua-simpleview
  name: "Let's Minocqua (Simpleview)"
  type: simpleview_html
  url: "https://www.minocqua.org/events/"

- id: vilas-county-tec
  name: "Vilas County Tourism (TEC)"
  type: tec_rest
  url: "https://vilaswi.com/"

- id: oneida-county-tec
  name: "Oneida County Tourism (TEC)"
  type: tec_rest
  url: "https://oneidacountywi.com/"
